services:
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:17.4
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
